import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import fs from 'node:fs';
import vm from 'node:vm';
const require=createRequire(import.meta.url);
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url))),origin='http://127.0.0.1:8793';
const server=spawn('python3',['-m','http.server','8793','--bind','127.0.0.1'],{cwd:root,stdio:'ignore'});
let browser;
try{
  for(let i=0;i<60;i++){try{await fetch(origin);break;}catch{await new Promise(resolve=>setTimeout(resolve,100));}}
  vm.runInThisContext(fs.readFileSync(path.join(root,'turtle/history-diff.js'),'utf8'));
  for(const [oldCode,newCode] of [['',''],['','a'],['a\nb\na','a\na\nb'],['x\n','x'],['a\nb\nc','a\nx\nc'],['q\n'.repeat(800),'z\n'.repeat(700)]]){
    const {rows}=globalThis.TurtleHistoryDiff(oldCode,newCode);
    assert.equal(rows.filter(row=>row.kind!=='added').map(row=>row.text).join('\n'),oldCode);
    assert.equal(rows.filter(row=>row.kind!=='removed').map(row=>row.text).join('\n'),newCode);
  }
  browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE||undefined,args:['--no-sandbox']});
  const context=await browser.newContext({viewport:{width:1600,height:1000}});
  const deps=[['**/codemirror.min.css','codemirror/lib/codemirror.css'],['**/codemirror.min.js','codemirror/lib/codemirror.js'],['**/mode/python/python.min.js','codemirror/mode/python/python.js'],['**/skulpt.min.js','skulpt/dist/skulpt.min.js'],['**/skulpt-stdlib.js','skulpt/dist/skulpt-stdlib.js']];
  for(const [pattern,file] of deps)await context.route(pattern,route=>route.fulfill({path:require.resolve(file)}));
  await context.route('**/googletagmanager.com/**',route=>route.abort());
  const oldCode='forward(35)\nleft(90)\nforward(60)',newCode='forward(50)\nleft(90)\nforward(60)';
  await context.addInitScript(({oldCode,newCode})=>{
    if(!location.pathname.startsWith('/turtle/')||localStorage.getItem('dsteckler-turtle-code-v1-history-v1'))return;
    localStorage.setItem('dsteckler-turtle-code-v1',newCode);
    localStorage.setItem('dsteckler-turtle-code-v1-history-v1',JSON.stringify([{time:Date.now()-1000,code:newCode,label:'Autosave'},{time:Date.now()-60000,code:oldCode,label:'Autosave'}]));
  },{oldCode,newCode});
  const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('dialog',dialog=>dialog.accept());
  await page.goto(origin+'/turtle/');await page.waitForFunction(()=>window.TurtleSidebar&&window.TurtleWorkbench);
  const editor=page.locator('.code-panel .CodeMirror'),preview=page.locator('.history-preview .CodeMirror');
  assert.equal(await editor.evaluate(element=>element.CodeMirror.getValue()),newCode);
  assert((await page.locator('.reference-topic').count())>=95);
  assert.equal(await page.locator('.reference-topic .reference-thumbnail').count(),await page.locator('.reference-topic').count());
  const sidebarBounds=await page.locator('#commandLibrary').boundingBox(),codeBounds=await editor.boundingBox();
  assert(sidebarBounds.x+sidebarBounds.width<=codeBounds.x);
  await page.locator('#commandSearch').fill('circle');
  assert((await page.locator('.reference-topic').count())>0);
  assert((await page.locator('.reference-topic').count())<95);
  await page.locator('#commandSearch').fill('');
  await page.locator('#codeHistoryBtn').click();assert(await page.locator('#historyPane').isVisible());
  assert.equal(await preview.evaluate(element=>element.CodeMirror.getValue()),newCode);
  await page.locator('.history-version').nth(1).hover();
  assert.equal(await preview.evaluate(element=>element.CodeMirror.getValue()),oldCode);
  assert.equal(await editor.evaluate(element=>element.CodeMirror.getValue()),newCode,'Hover leaves the working editor intact');
  await page.locator('.history-version').first().click();await page.locator('#historyView').selectOption('diff');
  assert.equal(await preview.evaluate(element=>element.CodeMirror.getValue()),'forward(35)\nforward(50)\nleft(90)\nforward(60)');
  assert.equal(await page.locator('.history-diff-added').count(),1);assert.equal(await page.locator('.history-diff-removed').count(),1);
  await page.locator('#historyView').selectOption('code');await page.locator('.history-version').nth(1).click();
  await page.locator('#restoreHistoryVersion').click();
  assert.equal(await editor.evaluate(element=>element.CodeMirror.getValue()),oldCode);
  assert(await page.evaluate(code=>TurtleWorkbench.readHistory().some(entry=>entry.code===code),newCode),'Restore retains the replaced code');
  await page.locator('#referenceTab').click();await page.locator('#commandSearch').fill('color');
  await page.locator('.reference-topic').filter({has:page.getByText('color()',{exact:true})}).click();
  assert(await page.getByRole('heading',{name:'color()',exact:true}).isVisible());
  await page.locator('.reference-example').filter({hasText:'Traffic lights'}).click();
  const reference=page.frameLocator('.reference-runner');
  await reference.locator('.code-panel .CodeMirror').waitFor();
  await page.waitForFunction(()=>document.querySelector('.reference-runner').contentWindow.TurtleWorkbench?.editor.getValue().includes('limegreen'));
  assert.equal(await editor.evaluate(element=>element.CodeMirror.getValue()),oldCode,'Preview leaves main code untouched');
  const previewSizes=await page.locator('.reference-runner').evaluate(frame=>{const doc=frame.contentDocument;return {code:doc.querySelector('.code-panel').getBoundingClientRect().width,world:doc.querySelector('.world-panel').getBoundingClientRect().width,width:frame.clientWidth};});
  assert(previewSizes.code>previewSizes.width*.3);assert(previewSizes.world>previewSizes.width*.3,'Drawing occupies a full pane in narrow reference embed');
  await page.waitForFunction(()=>document.querySelector('.reference-runner').contentDocument.getElementById('codeStatus').classList.contains('good'));
  assert.equal(await page.locator('.reference-runner-actions button').count(),3);
  await page.getByRole('button',{name:'Load into main editor',exact:true}).click();
  const loaded=await editor.evaluate(element=>element.CodeMirror.getValue());assert.match(loaded,/limegreen/);
  assert(await page.evaluate(code=>TurtleWorkbench.readHistory().some(entry=>entry.code===code),oldCode));
  await editor.evaluate(element=>{element.CodeMirror.setValue('forward(137)\nleft(42)');});
  await page.locator('#clearCodeBtn').click();assert.equal(await editor.evaluate(element=>element.CodeMirror.getValue()),'');
  await page.locator('#codeHistoryBtn').click();
  const index=await page.evaluate(()=>TurtleWorkbench.readHistory().findIndex(entry=>entry.code==='forward(137)\nleft(42)'));assert(index>=0);
  await page.locator('.history-version').nth(index).click();await page.locator('#restoreHistoryVersion').click();
  assert.equal(await editor.evaluate(element=>element.CodeMirror.getValue()),'forward(137)\nleft(42)');
  await page.reload();await page.waitForFunction(()=>window.TurtleSidebar);assert.equal(await editor.evaluate(element=>element.CodeMirror.getValue()),'forward(137)\nleft(42)');
  await page.locator('#referenceTab').click();await page.locator('#commandSearch').fill('radius');assert((await page.locator('.reference-topic').count())>0);
  await page.locator('#commandSearch').fill('zz-no-matching-command');assert(await page.locator('#commandEmpty').isVisible());
  await page.locator('#commandSearch').fill('');
  await page.locator('#commandSearch').fill('forward');await page.locator('.reference-topic').filter({has:page.getByText('forward()',{exact:true})}).click();
  await page.waitForFunction(()=>document.querySelector('.reference-runner').contentWindow.TurtleWorkbench?.editor.getValue().includes('forward(100)'));
  await page.getByRole('button',{name:'Load into main editor',exact:true}).click();
  assert.match(await editor.evaluate(element=>element.CodeMirror.getValue()),/^pensize\(4\)\nforward\(100\)/);
  await page.locator('#runBtn').click();await page.waitForFunction(()=>document.getElementById('codeStatus').classList.contains('good'));assert(!await page.locator('.error-card').count());
  const displayCode=await editor.evaluate(element=>element.CodeMirror.getValue());
  const initialWorld=await page.locator('#worldScaleBox').evaluate(element=>element.getBoundingClientRect().width);
  async function slide(id,value){await page.locator('#'+id).evaluate((element,value)=>{element.value=String(value);element.dispatchEvent(new Event('input',{bubbles:true}));},value);}
  await slide('codeFontSize',32);assert.equal(await editor.evaluate(element=>getComputedStyle(element).fontSize),'32px');
  await page.getByRole('button',{name:'Increase code size',exact:true}).click();assert.equal(await page.locator('#codeFontSize').inputValue(),'34');
  await page.getByRole('button',{name:'Decrease code size',exact:true}).click();assert.equal(await page.locator('#codeFontSize').inputValue(),'32');
  await slide('outputFontSize',30);assert.equal(await page.locator('#output').evaluate(element=>getComputedStyle(element).fontSize),'30px');
  await slide('drawingZoom',200);assert(Math.abs((await page.locator('#worldScaleBox').evaluate(element=>element.getBoundingClientRect().width))-initialWorld*2)<2);
  await slide('drawingZoom',300);assert.equal(await page.locator('#worldStage').evaluate(element=>getComputedStyle(element).overflow),'auto');
  assert(await page.getByRole('button',{name:'Increase drawing zoom',exact:true}).isDisabled());
  assert.equal(await editor.evaluate(element=>element.CodeMirror.getValue()),displayCode,'Display controls preserve the program');
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Zoom stays inside the drawing panel');
  await page.reload();await page.waitForFunction(()=>window.TurtleSidebar);
  assert.equal(await page.locator('#codeFontSize').inputValue(),'32');assert.equal(await page.locator('#drawingZoom').inputValue(),'300');assert.equal(await page.locator('#outputFontSize').inputValue(),'30');
  assert.equal(await editor.evaluate(element=>element.CodeMirror.getValue()),displayCode);
  await page.locator('#codeHistoryBtn').click();
  assert((await page.locator('#commandLibrary').boundingBox()).width>=500);
  if(process.env.TURTLE_SIDEBAR_PROOF){fs.mkdirSync(process.env.TURTLE_SIDEBAR_PROOF,{recursive:true});await page.screenshot({path:path.join(process.env.TURTLE_SIDEBAR_PROOF,'history-desktop.png')});}
  await page.setViewportSize({width:390,height:844});
  assert(await page.locator('#historyPane').isVisible());const box=await page.locator('#commandLibrary').boundingBox();assert(box.width<=390);
  await page.locator('#historyTab').press('ArrowLeft');assert(await page.locator('#referencePane').isVisible());
  await page.locator('#referenceTab').press('ArrowRight');assert(await page.locator('#historyPane').isVisible());
  if(process.env.TURTLE_SIDEBAR_PROOF)await page.screenshot({path:path.join(process.env.TURTLE_SIDEBAR_PROOF,'history-mobile.png')});
  await page.locator('#commandsClose').click();await page.locator('#codeHistoryBtn').click();assert(await page.locator('#historyPane').isVisible());
  await page.locator('#commandsClose').click();
  assert(await page.locator('#codeFontSize').isVisible());assert(await page.locator('#drawingZoom').isVisible());assert(await page.locator('#outputFontSize').isVisible());
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile display controls fit the page');
  await page.locator('#resetLayout').click();assert.equal(await editor.evaluate(element=>getComputedStyle(element).fontSize),'16px');
  assert.equal(await page.locator('#drawingZoom').inputValue(),'100');assert.equal(await page.locator('#outputFontSize').inputValue(),'14');
  assert.equal(await editor.evaluate(element=>element.CodeMirror.getValue()),displayCode,'Reset view preserves code');
  assert.deepEqual(errors,[]);
  console.log('PASS shared reference, single example action, legacy history, hover previews, diffs, restore, immediate clear, reload, Python run, independent zoom, saved sizes, reset, keyboard tabs, desktop and mobile.');
}finally{await browser?.close();server.kill();}
