"""Build safe lesson boundaries from the gallery's actual Python programs.

Run: python turtledemo/build-tutorial-steps.py
No Python statement or filled shape is split between steps.
"""
import ast
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent
source = r"""
const fs=require('fs'),vm=require('vm');const c={window:{}};vm.createContext(c);
for(const f of ['base-catalog.js',...'abcdef'.split('').map(x=>'curated-'+x+'.js')])
  vm.runInContext(fs.readFileSync(f,'utf8'),c);
process.stdout.write(JSON.stringify([...c.window.TURTLE_BASE_CATALOG,...c.window.CURATED_EXAMPLES]));
"""
catalog = json.loads(subprocess.check_output(['node', '-e', source], cwd=ROOT))

def call_name(node):
    if isinstance(node, ast.Expr) and isinstance(node.value, ast.Call):
        return getattr(node.value.func, 'id', '')
    return ''

def make_steps(code):
    nodes = ast.parse(code).body
    lines = code.splitlines()
    ends, last, filled = [], 0, 0
    for i, node in enumerate(nodes):
        name = call_name(node)
        if name == 'begin_fill':
            filled += 1
        if name == 'end_fill':
            filled = max(0, filled - 1)
        nxt = nodes[i+1] if i+1 < len(nodes) else None
        if not nxt:
            ends.append(len(lines))
            break
        between = lines[node.end_lineno:nxt.lineno-1]
        comment_boundary = any(line.startswith('# ') for line in between)
        setup_names = {'speed', 'pensize', 'bgcolor', 'color', 'hideturtle', 'shape'}
        setup = all(isinstance(n, (ast.Import, ast.ImportFrom, ast.Assign)) or call_name(n) in setup_names for n in nodes[:i+1])
        setup_end = setup and not (isinstance(nxt, (ast.Import, ast.ImportFrom, ast.Assign)) or call_name(nxt) in setup_names)
        function_end = isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
        long_enough = node.end_lineno-last >= 16
        if not filled and (setup_end or function_end or comment_boundary or long_enough):
            ends.append(node.end_lineno)
            last = node.end_lineno
    result = []
    start = 0
    for end in ends:
        block = '\n'.join(lines[start:end]).strip()
        if not block:
            continue
        # Every cumulative step must remain syntactically runnable.
        compile('\n'.join(lines[:end]), '<tutorial>', 'exec')
        block_nodes = ast.parse(block).body
        comments = [line[2:].strip().rstrip('.') for line in block.splitlines() if line.startswith('# ')]
        funcs = [n.name for n in block_nodes if isinstance(n, ast.FunctionDef)]
        if start == 0 and all(isinstance(n, (ast.Import, ast.ImportFrom, ast.Assign)) or call_name(n) in {'speed','pensize','bgcolor','color','hideturtle','shape'} for n in block_nodes):
            title, kind = 'Get ready', 'setup'
        elif funcs:
            title, kind = 'Define '+', '.join(funcs), 'function'
        elif comments:
            title, kind = comments[0], 'draw'
        elif any(isinstance(n, (ast.For, ast.While)) for n in block_nodes):
            title, kind = 'Build the pattern', 'loop'
        elif not result or (len(result) and all(s['kind'] in ('setup','function') for s in result)):
            title, kind = 'Start the drawing', 'draw'
        elif end == len(lines):
            title, kind = 'Finish the details', 'draw'
        else:
            title, kind = 'Add the next shapes', 'draw'
        result.append({'end': end, 'title': title, 'kind': kind})
        start = end
    return result

plans = {p['id']: make_steps(p['code']) for p in catalog}
output = '// Generated by build-tutorial-steps.py; line numbers refer to the gallery code.\nwindow.TURTLE_STEP_PLANS=' + json.dumps(plans, separators=(',',':'), ensure_ascii=False) + ';\n'
(ROOT/'tutorial-steps.js').write_text(output)
print(f'Built {sum(map(len, plans.values()))} runnable steps for {len(plans)} projects.')
