import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import Lab from './app/lab';
import {configured,hasSession,identify,signIn,signOut,studentCredentials,setupTeacher,Identity} from './app/cloud';
import './app/globals.css';
import './app/lab.css';
const initialSetup=new URLSearchParams(location.hash.slice(1)).get('setup')||'';
if(initialSetup)history.replaceState(null,'',location.pathname+location.search);
function App(){const [setup,setSetup]=useState(initialSetup),[setupDone,setSetupDone]=useState(false);const [identity,setIdentity]=useState<Identity|null>(null),[teacher,setTeacher]=useState(false),[classCode,setClassCode]=useState(localStorage.getItem('keyquest-class')||''),[code,setCode]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[checking,setChecking]=useState(configured&&hasSession());useEffect(()=>{if(configured&&hasSession())identify().then(setIdentity).catch(e=>setError(e.message)).finally(()=>setChecking(false))},[]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const credentials=teacher?{email:email.trim(),password}:await studentCredentials(classCode,code);const who=await signIn(credentials.email,credentials.password);if(teacher&&who.role!=='teacher'){await signOut();throw Error('Use the student sign-in for this account.')}if(!teacher)localStorage.setItem('keyquest-class',classCode.toLowerCase().replace(/\s/g,''));setIdentity(who);setPassword('');setCode('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function finishSetup(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await setupTeacher(setup,email,password);setSetup('');setTeacher(true);setSetupDone(true);setPassword('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 if(setup)return <div className="lab auth-page"><section className="auth-card"><span className="pill">KEYQUEST · TEACHER SETUP</span><h1>Open your classroom</h1><p>Choose your teacher login. You will create student codes after signing in.</p><form onSubmit={finishSetup}><label htmlFor="setup-email">Your email</label><input id="setup-email" type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/><label htmlFor="setup-password">Choose a password</label><input id="setup-password" type="password" autoComplete="new-password" minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)} required/><p className="small-note">Use at least 12 characters. Save your password somewhere you can find it.</p>{error&&<p role="alert" className="error">{error}</p>}<button disabled={busy}>{busy?'Creating…':'Create my teacher login'}</button></form><button className="text-button" onClick={()=>{setSetup('');setTeacher(true);setError('')}}>I already created my account</button></section></div>;
 if(checking)return <div className="auth-page"><h1>Opening your classroom…</h1></div>;
 if(identity)return <Lab identity={identity} onSignOut={async()=>{try{await signOut()}catch{}setIdentity(null)}}/>;
 return <div className="lab auth-page"><section className="auth-card"><span className="pill">KEYQUEST · TYPING LAB</span><h1>{teacher?'Teacher sign-in':'Ready for your next session?'}</h1>{!configured?<><p>The classroom connection is being set up. You can explore the lessons in practice mode.</p><button onClick={()=>setIdentity({role:'demo',name:'Practice visitor',classCode:'',userId:''})}>Try the lessons</button><p className="small-note">Practice mode does not save results online.</p></>:<>{setupDone&&<p role="status">Your teacher account is ready. Sign in below.</p>}<p>{teacher?'Sign in to manage your class and view progress.':'Enter the codes on your card.'}</p><form onSubmit={login}>{teacher?<><label htmlFor="email">Teacher email</label><input id="email" type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/><label htmlFor="password">Password</label><input id="password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></>:<><label htmlFor="class">Class code</label><input id="class" autoCapitalize="none" autoComplete="off" maxLength={6} value={classCode} onChange={e=>setClassCode(e.target.value)} placeholder="6 letters / numbers" required/><label htmlFor="code">My student code</label><input id="code" type="password" inputMode="numeric" autoComplete="off" maxLength={8} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="8 numbers" required/></>}{error&&<p role="alert" className="error">{error}</p>}<button disabled={busy}>{busy?'Opening…':'Sign in'}</button></form><button className="text-button" onClick={()=>{setTeacher(!teacher);setError('')}}>{teacher?'Back to student sign-in':'I am the teacher'}</button></>}</section></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
