"""Rebuild the shared gallery catalog, learning levels and starter art."""
import ast
import json
from pathlib import Path
from lessons_starters import starter_projects
from project_art import revisions

ROOT=Path(__file__).resolve().parent

def read(name):
    s=(ROOT/name).read_text()
    marker='=[' if name=='base-catalog.js' else '.concat(['
    start=s.index(marker)+len(marker)-1
    return json.JSONDecoder().raw_decode(s[start:])[0]

def metadata(p):
    if p['id'].startswith('starter-'):
        return {k:p[k] for k in ['level','style','skills','order']}
    tree=ast.parse(p['code'])
    nodes=list(ast.walk(tree))
    funcs=[n for n in nodes if isinstance(n,ast.FunctionDef)]
    names={n.func.id for n in nodes if isinstance(n,ast.Call) and isinstance(n.func,ast.Name)}
    math=any(isinstance(n,ast.Attribute) and isinstance(n.value,ast.Name) and n.value.id=='math' for n in nodes)
    recursive=any(any(isinstance(c,ast.Call) and isinstance(c.func,ast.Name) and c.func.id==n.name for c in ast.walk(n)) for n in funcs)
    nested=any(isinstance(n,ast.For) and any(isinstance(x,ast.For) for c in n.body for x in ast.walk(c)) for n in nodes)
    pairs=sum(len(n.elts) for n in nodes if isinstance(n,ast.List) and n.elts and all(isinstance(x,ast.Tuple) for x in n.elts))
    many_points=pairs>=28
    hard=recursive or (math and p['category'] in ['Math','Science','Art']) or many_points or (nested and len(p['code'].splitlines())>70)
    skills=[]
    if recursive:skills.append('recursion')
    if math:skills.append('curve math')
    if nested:skills.append('nested loops')
    elif 'range' in names:skills.append('loops')
    if funcs:skills.append('functions')
    if 'goto' in names:skills.append('coordinates')
    if not skills:skills=['movement','color']
    return {'level':'Hard' if hard else 'Medium','style':'Math & patterns' if p['category']=='Math' or recursive else 'Coordinate drawing' if pairs>=10 or funcs and 'goto' in names else 'Moves & shapes','skills':skills[:4]}

def main():
    sources=['base-catalog.js']+['curated-'+c+'.js' for c in 'abcdef']
    groups={f:read(f) for f in sources}
    catalog=[p for group in groups.values() for p in group]
    changes=revisions(catalog)
    for file,group in groups.items():
        for p in group:p.update(changes.get(p['id'],{}))
        data=json.dumps(group,separators=(',',':'),ensure_ascii=False)
        (ROOT/file).write_text('window.TURTLE_BASE_CATALOG='+data+';\n' if file=='base-catalog.js' else 'window.CURATED_EXAMPLES=(window.CURATED_EXAMPLES||[]).concat('+data+');\n')
    starters=starter_projects()
    (ROOT/'starter-catalog.js').write_text('// Generated by build-project-catalog.py.\nwindow.TURTLE_STARTER_CATALOG='+json.dumps([{k:v for k,v in p.items() if k!='steps'} for p in starters],separators=(',',':'),ensure_ascii=False)+';\n')
    meta={p['id']:metadata(p) for p in catalog+starters}
    meta['robot-roll-call']={'level':'Medium','style':'Moves & shapes','skills':['loops','functions','coordinates']}
    (ROOT/'project-levels.js').write_text('// Generated from the project code and authored starter sequence.\nwindow.TURTLE_PROJECT_LEVELS='+json.dumps(meta,separators=(',',':'),ensure_ascii=False)+';\n')
    from collections import Counter
    print('Levels:',dict(Counter(p['level'] for p in meta.values())))
    print('Art revisions:',len(changes),'New beginners:',len(starters))
if __name__=='__main__':main()
