import assert from 'node:assert/strict';
import {lessons,phases} from '../app/curriculum.ts';
import {runClassroomPython} from '../app/code-lab.ts';
assert.equal(lessons.length,50);
assert.equal(phases.reduce((sum,p)=>sum+p.minutes,0),42);
for(const l of lessons)assert(l.choices.includes(l.answer));
assert.equal(runClassroomPython(lessons[37].example).output,'1\n2');
assert(runClassroomPython('import os').error);
const saved=new Map();globalThis.sessionStorage={getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v),removeItem:k=>saved.delete(k)};
globalThis.window={KEYQUEST_CONFIG:{supabaseUrl:'https://test.invalid',supabasePublishableKey:'public-test-key'}};
const calls=[];
globalThis.fetch=async(url,opts={})=>{calls.push({url,opts});
 if(url.includes('/auth/v1/token'))return Response.json({access_token:'test-access',refresh_token:'test-refresh',expires_in:3600});
 if(url.endsWith('/auth/v1/user'))return Response.json({id:'student-1'});
 if(url.includes('/kq_teachers'))return Response.json([]);
 if(url.includes('/kq_learners'))return Response.json([{id:'learner-1',name:'Blue Fox'}]);
 if(url.includes('/kq_sessions')&&opts.method==='POST')return new Response(null,{status:201});
 if(url.includes('/kq_sessions')){const start=Number(opts.headers.Range.split('-')[0]);return Response.json(Array.from({length:Math.min(500,1001-start)},(_,i)=>({id:'s'+(start+i),learner:'learner-1',lesson:1,payload:{correct:20},created:'2026-09-09'})));}
 if(url.includes('/logout'))return new Response(null,{status:204});
 throw Error('Unexpected request: '+url);
};
const cloud=await import('../app/cloud.ts');
const a=await cloud.studentCredentials('ABC123','12345678');
const b=await cloud.studentCredentials('abc123','1234 5678');
assert.deepEqual(a,b);assert(a.email.endsWith('@students.keyquest.invalid'));assert(!a.email.includes('12345678'));assert.equal(a.password,'Kq!abc123:12345678');
await assert.rejects(cloud.studentCredentials('abc123','12'));
const identity=await cloud.signIn(a.email,a.password);assert.equal(identity.role,'student');assert.equal(identity.name,'Blue Fox');
const r=await cloud.progressRequest('/progress');const body=await r.json();assert.equal(body.sessions.length,1001);assert.equal(body.learners.length,1);
const write=await cloud.progressRequest('/progress',{body:JSON.stringify({action:'session',session:{id:'s1',learner:'learner-1',lesson:2,correct:20}})});assert.equal((await write.json()).saved,true);
const posted=calls.find(c=>c.opts.method==='POST'&&c.url.includes('/kq_sessions'));assert.equal(JSON.parse(posted.opts.body).learner,'learner-1');assert.equal(posted.opts.headers.Prefer,'resolution=ignore-duplicates,return=minimal');
await cloud.signOut();assert.equal(cloud.hasSession(),false);assert.equal(saved.has('keyquest-auth'),false);
console.log('Passed curriculum, interpreter, code normalization, student identity, 1,001-record pagination, idempotent save request, and sign-out checks. Supabase authorization still requires live verification.');
