declare global {interface Window {KEYQUEST_CONFIG?:{supabaseUrl:string;supabasePublishableKey:string}}}
type Token={access_token:string;refresh_token:string;expires_at:number};
export type Identity={role:'teacher'|'student'|'demo';classCode:string;name:string;userId:string};
const config=window.KEYQUEST_CONFIG;
export const configured=!!config?.supabaseUrl&&!!config?.supabasePublishableKey;
const base=(config?.supabaseUrl||'').replace(/\/$/,'');
const key=config?.supabasePublishableKey||'';
let session:Token|null=null;try{session=JSON.parse(sessionStorage.getItem('keyquest-auth')||'null')}catch{}
function remember(t:any){session={access_token:t.access_token,refresh_token:t.refresh_token,expires_at:Date.now()+t.expires_in*1000};sessionStorage.setItem('keyquest-auth',JSON.stringify(session));}
export function hasSession(){return !!session}
export function clearSession(){session=null;sessionStorage.removeItem('keyquest-auth');}
let refreshing:Promise<void>|null=null;
async function refresh(){if(!session)throw Error('Please sign in again.');if(!refreshing)refreshing=(async()=>{const r=await fetch(base+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session!.refresh_token})});const b=await r.json();if(!r.ok){clearSession();throw Error('Please sign in again. Your session has ended.')}remember(b)})().finally(()=>{refreshing=null});return refreshing}
export async function request(path:string,options:RequestInit={},retry=true):Promise<any>{if(!configured)throw Error('This classroom is not connected yet.');if(!session)throw Error('Please sign in.');if(session.expires_at<Date.now()+30000)await refresh();const r=await fetch(base+path,{...options,headers:{apikey:key,Authorization:'Bearer '+session!.access_token,'Content-Type':'application/json',...options.headers}});if(r.status===401&&retry){await refresh();return request(path,options,false)}const text=await r.text();let body:any={};try{body=text?JSON.parse(text):{}}catch{throw Error('The server returned an unexpected response. Try again.')}if(!r.ok)throw Error(body.error||body.message||'The request did not finish. Please try again.');return body;}
export async function studentCredentials(classCode:string,studentCode:string){const c=classCode.toLowerCase().replace(/\s/g,''),s=studentCode.replace(/\s/g,'');if(!/^[a-z0-9]{6}$/.test(c)||!/^\d{8}$/.test(s))throw Error('Use your six-character class code and eight-digit student code.');const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(c+':'+s));const hex=Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('');return {email:hex+'@students.keyquest.invalid',password:'Kq!'+c+':'+s};}
export async function signIn(email:string,password:string){if(!configured)throw Error('Your classroom is not connected yet.');const r=await fetch(base+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({email,password})});const b=await r.json();if(!r.ok)throw Error(r.status===429?'Too many tries. Wait a little, then try again.':'Those sign-in details did not match. Please check and try again.');remember(b);try{return await identify()}catch(e){await signOut();throw e}}
export async function identify():Promise<Identity>{const user=await request('/auth/v1/user');const teachers=await request('/rest/v1/kq_teachers?select=class_code,name&user_id=eq.'+user.id);if(teachers[0])return {role:'teacher',classCode:teachers[0].class_code,name:teachers[0].name,userId:user.id};const students=await request('/rest/v1/kq_learners?select=id,name&user_id=eq.'+user.id);if(!students[0])throw Error('This account has not been assigned to a classroom. Ask your teacher for help.');return {role:'student',classCode:'',name:students[0].name,userId:user.id};}
export async function signOut(){try{if(session)await request('/auth/v1/logout?scope=local',{method:'POST'})}finally{clearSession()}}
async function allSessions(){const all:any[]=[];for(let from=0;;from+=500){const batch=await request('/rest/v1/kq_sessions?select=id,learner,lesson,payload,created&order=created.asc,id.asc',{headers:{Range:`${from}-${from+499}`,'Range-Unit':'items'}});all.push(...batch);if(batch.length<500)return all;}}
export async function progressRequest(_url:string,options?:RequestInit){try{if(!options){const [learners,sessions]=await Promise.all([request('/rest/v1/kq_learners?select=id,name&order=created.asc'),allSessions()]);return Response.json({learners,sessions:sessions.map((r:any)=>({...r.payload,id:r.id,learner:r.learner,lesson:r.lesson,created:r.created}))});}const b=JSON.parse(String(options.body));if(b.action==='learner'){const data=await request('/functions/v1/keyquest-admin',{method:'POST',body:JSON.stringify({action:'create',name:b.name})});return Response.json(data)}if(b.action==='session'){const s=b.session;await request('/rest/v1/kq_sessions?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify({id:s.id,learner:s.learner,lesson:s.lesson,payload:s})});return Response.json({saved:true})}throw Error('Unknown action.')}catch(e:any){return Response.json({error:e.message||'Could not connect. Your work remains on this screen.'},{status:503})}}
