'use client';
import {useState,useEffect,useRef} from 'react';
import {Keyboard,Volume2,Play,Pause,ChevronRight,Check,Star,BookOpen,BarChart3,Settings2,Download,Plus,UserRound,Target,RotateCcw,CheckCircle2,Hand,Clock,HelpCircle} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {lessons,units,phases,benchmark,warmup,Lesson} from './curriculum';
import './lab.css';
import {progressRequest,request,Identity} from './cloud';
import {runClassroomPython} from './code-lab';
type Learner={id:string;name:string};
type Metrics={correct:number;attempts:number;seconds:number;errors:Record<string,number>};
type Result={id:string;learner:string;lesson:number;created:string;correct:number;attempts:number;seconds:number;errors:Record<string,number>;benchmark:Metrics;mode:string;check:string;checkCorrect:boolean;draft:string;reflection:string;complete:boolean;benchmarkComplete:boolean};
const empty=():Metrics=>({correct:0,attempts:0,seconds:0,errors:{}});
const wpm=(m:Metrics)=>m.seconds?Math.round(m.correct/5/(m.seconds/60)*10)/10:0;
const accuracy=(m:{correct:number;attempts:number})=>m.attempts?Math.round(m.correct/m.attempts*100):0;
const clock=(s:number)=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
function speak(text:string,onError:(s:string)=>void){if(!('speechSynthesis' in window)){onError('Read-aloud is unavailable on this browser. Ask someone to read the directions with you.');return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.8;u.onerror=()=>onError('Read-aloud could not start. You can still read the directions on screen.');speechSynthesis.speak(u);}
function KeyBoard({next}:{next:string}){const rows=['1234567890','qwertyuiop','asdfghjkl','zxcvbnm'];const upper=/[A-Z]/.test(next)||'():">'.includes(next)&&!!next;const mapped:Record<string,string>={'(':'9',')':'0',':':';','"':"'",'>':'.'};const key=(mapped[next]||next).toLowerCase();return <div className="keyboard" aria-label="Keyboard guide"><div className="keyrows">{rows.map((r,i)=><div className="keyrow" key={r}>{i===3&&<kbd className={upper?'lit wide':'wide'}>shift</kbd>}{r.split('').map(k=><kbd key={k} className={`${key===k?'lit':''} ${k==='f'||k==='j'?'bump':''}`}>{k}</kbd>)}{i===2&&<><kbd className={key===';'?'lit':''}>;</kbd><kbd className={key==="'"?'lit':''}>'</kbd></>}{i===3&&<kbd className={key==='.'?'lit':''}>.</kbd>}</div>)}<div className="keyrow"><kbd className={next===' '?'space lit':'space'}>space</kbd><kbd className={next==='\n'?'lit wide':'wide'}>enter</kbd></div></div></div>}
function Trend({results}:{results:Result[]}){const data=results.filter(r=>r.benchmarkComplete).slice(-15);if(!data.length)return <div className="empty-chart"><BarChart3/><h3>Your first check starts your chart.</h3><p>Finish a two-minute typing check to see a point here.</p></div>;const max=Math.max(8,...data.map(r=>wpm(r.benchmark)))*1.2;const points=data.map((r,i)=>`${45+i*(530/Math.max(1,data.length-1))},${170-wpm(r.benchmark)/max*140}`);return <><svg viewBox="0 0 620 210" role="img" aria-label={`Last ${data.length} complete typing checks: ${data.map(r=>wpm(r.benchmark)+' words per minute').join(', ')}`} className="trend">{[0,1,2,3].map(i=><g key={i}><line x1="45" x2="590" y1={170-i*45} y2={170-i*45} stroke="#dce3ef"/><text x="3" y={175-i*45}>{Math.round(max*i*45/140)}</text></g>)}<polyline points={points.join(' ')} fill="none" stroke="#3158d5" strokeWidth="3"/>{data.map((r,i)=><g key={r.id}><circle cx={45+i*(530/Math.max(1,data.length-1))} cy={170-wpm(r.benchmark)/max*140} r="5" fill="#3158d5"/><text x={45+i*(530/Math.max(1,data.length-1))} y="199" textAnchor="middle">{i+1}</text></g>)}</svg><p className="muted">WPM · Most recent complete checks, oldest to newest</p></>}
export default function Lab({identity,onSignOut}:{identity:Identity;onSignOut:()=>void}){
 const [lastCode,setLastCode]=useState<{name:string;code:string}|null>(null),[tab,setTab]=useState('today'),[lessonId,setLessonId]=useState(1),[phase,setPhase]=useState(0),[active,setActive]=useState(false),[paused,setPaused]=useState(false),[phaseSeconds,setPhaseSeconds]=useState(0),[running,setRunning]=useState(false),[pos,setPos]=useState(0),[round,setRound]=useState(0),[flash,setFlash]=useState(''),[notice,setNotice]=useState(''),[mode,setMode]=useState('words'),[large,setLarge]=useState(false),[showKeys,setShowKeys]=useState(true),[lessonOpen,setLessonOpen]=useState(false),[profilesOpen,setProfilesOpen]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[learners,setLearners]=useState<Learner[]>([]),[learner,setLearner]=useState<Learner|null>(null),[results,setResults]=useState<Result[]>([]),[loadError,setLoadError]=useState(''),[loading,setLoading]=useState(true),[newName,setNewName]=useState(''),[busy,setBusy]=useState(false),[draft,setDraft]=useState(''),[reflection,setReflection]=useState(''),[check,setCheck]=useState(''),[checkSubmitted,setCheckSubmitted]=useState(false),[metrics,setMetrics]=useState<Metrics>(empty),[bench,setBench]=useState<Metrics>(empty),[benchStarted,setBenchStarted]=useState(false),[report,setReport]=useState<Result|null>(null),[saveState,setSaveState]=useState(''),[saved,setSaved]=useState(false),[confirmExit,setConfirmExit]=useState(false),[codeOutput,setCodeOutput]=useState<{output:string;error?:string}|null>(null);
 const capture=useRef<HTMLInputElement>(null);const lesson=lessons[lessonId-1],unit=units[lesson.unit],stage=phases[phase];
 const myResults=results.filter(r=>r.learner===learner?.id);const completeIds=new Set(myResults.filter(r=>r.complete).map(r=>r.lesson));const comparable=myResults.filter(r=>r.benchmarkComplete);const latest=comparable.at(-1);const first=comparable[0];const gain=latest&&first?Math.round((wpm(latest.benchmark)-wpm(first.benchmark))*10)/10:0;
 const benchDone=bench.seconds>=120;const isTyping=active&&!report&&(stage.kind==='type'||stage.kind==='benchmark');
 let pool=phase===1?warmup(lessonId):mode==='letters'?lesson.words.flatMap(w=>w.split('').filter(c=>c!==' ')):mode==='words'?lesson.words:lesson.phrases;
 const target=phase===8?benchmark:pool[round%pool.length];const next=target[pos]||' ';
 async function load(){if(identity.role==='demo'){setLoading(false);return;}setLoading(true);setLoadError('');try{const r=await progressRequest('/progress');const b=await r.json() as {error?:string;learners:Learner[];sessions:Result[]};if(!r.ok)throw new Error(b.error);setLearners(b.learners);setResults(b.sessions);if(identity.role==='student'&&b.learners[0]){setLearner(b.learners[0]);const done=b.sessions.filter(r=>r.complete).map(r=>r.lesson);setLessonId(Math.min(50,Math.max(0,...done)+1));}}catch(e:any){setLoadError(e.message||'Could not load progress.');}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{const pref=localStorage.getItem('keyquest-preferences');if(pref)try{const p=JSON.parse(pref);setLarge(!!p.large);setShowKeys(p.keys!==false);setMode(['letters','words','phrases'].includes(p.mode)?p.mode:'words')}catch{}},[]);
 useEffect(()=>{localStorage.setItem('keyquest-preferences',JSON.stringify({large,keys:showKeys,mode}))},[large,showKeys,mode]);
 useEffect(()=>{if(!active||report)return;const stop=()=>{if(document.hidden){setPaused(true);setRunning(false)}};const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};document.addEventListener('visibilitychange',stop);window.addEventListener('beforeunload',warn);return()=>{document.removeEventListener('visibilitychange',stop);window.removeEventListener('beforeunload',warn)}},[active,report]);
 useEffect(()=>{if(!active||paused||report)return;let previous=performance.now();const timer=setInterval(()=>{const now=performance.now();const delta=Math.min(2,(now-previous)/1000);previous=now;if(phase!==8||benchStarted)setPhaseSeconds(s=>s+delta);if(isTyping&&running){if(phase===8)setBench(m=>({...m,seconds:Math.min(120,m.seconds+delta)}));else setMetrics(m=>({...m,seconds:m.seconds+delta}));}},250);return()=>clearInterval(timer)},[active,paused,report,running,phase,benchStarted,isTyping]);
 useEffect(()=>{if(benchDone){setRunning(false);setFlash('Your two-minute check is complete.')}},[benchDone]);
 useEffect(()=>{if(!active||paused||report||phase===8||phase===9)return;if(phaseSeconds>=stage.minutes*60)movePhase()},[phaseSeconds]);
 useEffect(()=>{if(isTyping&&!paused)capture.current?.focus()},[phase,active,paused,round,isTyping]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),8000);return()=>clearTimeout(t)},[notice]);
 function movePhase(){setPhase(p=>Math.min(9,p+1));setPhaseSeconds(0);setRunning(false);setRound(0);setPos(0);setFlash('');setBenchStarted(false)}
 function start(){setBenchStarted(false);setFlash('');setActive(true);setPhase(0);setPaused(false);setPhaseSeconds(0);setMetrics(empty());setBench(empty());setRound(0);setPos(0);setRunning(false);setReport(null);setSaved(false);setSaveState('');setDraft('');setCodeOutput(null);setReflection('');setCheck('');setCheckSubmitted(false)}
 function input(key:string){if(!isTyping||paused||(phase===8&&(!benchStarted||benchDone)))return;if(key.length!==1)return;setRunning(true);const hit=key===next;const update=(m:Metrics)=>({...m,attempts:m.attempts+1,correct:m.correct+(hit?1:0),errors:hit?m.errors:{...m.errors,[next]:(m.errors[next]||0)+1}});if(phase===8)setBench(update);else setMetrics(update);if(hit){setFlash('');if(pos===target.length-1){setRound(r=>r+1);setPos(0);if(phase!==8)setFlash('Nice work. Here is the next one.')}else setPos(p=>p+1)}else setFlash(next===' '?'Tap the space bar once.':`Try ${next==='\n'?'Enter':next} again.`)}
 function keydown(e:React.KeyboardEvent<HTMLInputElement>){if(e.ctrlKey||e.altKey||e.metaKey||e.key==='Tab')return;if(e.repeat){e.preventDefault();return;}if(e.key==='Backspace'){e.preventDefault();return;}if(e.key==='Enter'){e.preventDefault();input('\n');return;}if(e.key.length===1){e.preventDefault();input(e.key)}}
 async function addLearner(){if(!newName.trim())return;setBusy(true);try{const r=await progressRequest('/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'learner',name:newName})});const b=await r.json() as Learner & {error?:string;studentCode?:string};if(!r.ok)throw new Error(b.error);setLearners(v=>[...v,b]);setLearner(b);if(b.studentCode)setLastCode({name:b.name,code:b.studentCode});setNewName('');setProfilesOpen(false);setLoadError('')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 function chooseLearner(l:Learner){setLearner(l);const done=results.filter(r=>r.learner===l.id&&r.complete).map(r=>r.lesson);if(!report)setLessonId(Math.min(50,Math.max(0,...done)+1));setProfilesOpen(false)}
 async function save(r:Result){if(!r.learner){setSaveState('This was a practice visit. Sign in with your student codes before your next session to save progress.');return;}setSaveState('Saving your work…');setBusy(true);try{const response=await progressRequest('/progress',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'session',session:r})});const b=await response.json() as {error?:string};if(!response.ok)throw new Error(b.error);setResults(old=>old.some(x=>x.id===r.id)?old:[...old,r]);setSaveState('Your progress is saved.');setSaved(true)}catch(e:any){setSaveState(e.message)}finally{setBusy(false)}}
 function finish(){const r:Result={id:crypto.randomUUID(),learner:learner?.id||'',lesson:lessonId,created:new Date().toISOString(),...metrics,seconds:Math.round(metrics.seconds),benchmark:{...bench,seconds:Math.round(bench.seconds)},mode:mode+(showKeys?' + key guide':' without key guide'),check,checkCorrect:checkSubmitted&&check.trim().toLowerCase()===lesson.answer,draft,reflection,complete:phase===9,benchmarkComplete:benchDone};setReport(r);setActive(false);setRunning(false);save(r)}
 function csvExport(){const rows=(tab==='teacher'?results:myResults);const header=['Nickname','Date','Session','Completed','Practice mode','Practice WPM','Accuracy','Active seconds','Check WPM','Check accuracy','Check seconds','Full benchmark','Concept answer','Correct answer','Writing','Reflection'];const quote=(v:unknown)=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const lines=rows.map(r=>[learners.find(l=>l.id===r.learner)?.name||'Learner',r.created,r.lesson,r.complete,r.mode,wpm(r as Metrics),accuracy(r),r.seconds,wpm(r.benchmark),accuracy(r.benchmark),r.benchmark.seconds,r.benchmarkComplete,r.check,r.checkCorrect,r.draft,r.reflection]);const blob=new Blob(['\ufeff'+[header,...lines].map(r=>r.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='keyquest-progress.csv';a.click();URL.revokeObjectURL(a.href)}
 const readButton=(text:string)=><button className="soft" onClick={()=>speak(text,setNotice)}><Volume2 size={18}/> Hear it</button>;
 return <div className={`lab ${large?'large-type':''}`}>
 <header className="topbar"><a className="brand" href="/" onClick={e=>{e.preventDefault();if(active){setConfirmExit(true)}else{setTab('today');setReport(null)}}}><span className="brand-icon"><Keyboard size={25}/></span><span>KeyQuest<span className="brand-sub">TYPING LAB</span></span></a><div className="top-actions"><span className="class-label">{identity.role==='teacher'?'Class '+identity.classCode:'Computer Science'}</span><button className="soft compact" disabled={active||!!report&&!saved&&identity.role!=='demo'} onClick={onSignOut}>Sign out</button><button className="profile" disabled={active||identity.role!=='teacher'} onClick={()=>setProfilesOpen(true)}><UserRound size={18}/>{learner?.name||'Choose your profile'}</button><button aria-label="Learning settings" className="icon-button" disabled={active} onClick={()=>setSettingsOpen(true)}><Settings2 size={20}/></button></div></header>
 <div className="page"><Tabs value={tab} onValueChange={v=>{if(active){setNotice('Finish your session before changing pages.');return}if(report&&!saved&&identity.role!=='demo'){setNotice('Save your result before changing pages.');return}setTab(v);setReport(null)}}><div className="navrow"><TabsList className="navigation"><TabsTrigger value="today"><Keyboard/>Today’s session</TabsTrigger><TabsTrigger value="journey"><BookOpen/>My journey</TabsTrigger><TabsTrigger value="progress"><BarChart3/>My progress</TabsTrigger>{identity.role==='teacher'&&<TabsTrigger value="teacher"><Settings2/>Teacher</TabsTrigger>}</TabsList><span className="course-label">50 sessions <span>·</span> 42 minutes each</span></div>
 {loadError&&identity.role==='student'&&<div className="notice"><p>{loadError}</p><button onClick={load}>Try again</button></div>}{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss message">×</button></div>}
 <TabsContent value="today">
 {report?<section className="report"><div className="report-top"><span className="achievement"><CheckCircle2 size={40}/></span><p className="eyebrow">SESSION {lessonId} · {report.complete?'FINISHED':identity.role==='demo'?'PRACTICE FINISHED':'PRACTICE SAVED'}</p><h1>You showed up and practiced.</h1><p>Here is what you did today{learner?`, ${learner.name}`:''}.</p></div><div className="metric-grid"><article><span>Typing check</span><strong>{report.benchmark.seconds?wpm(report.benchmark):'—'} <small>WPM</small></strong><p>{report.benchmarkComplete?'Full two-minute check':'Partial / not completed'}</p></article><article><span>Check accuracy</span><strong>{report.benchmark.attempts?accuracy(report.benchmark)+'%':'—'}</strong><p>{report.benchmark.correct} correct key presses</p></article><article><span>Practice time</span><strong>{clock(report.seconds)}</strong><p>{accuracy(report)}% practice accuracy</p></article><article><span>Idea check</span><strong>{checkSubmitted?(report.checkCorrect?'Got it':'Keep exploring'):'Not tried'}</strong><p>{checkSubmitted?lesson.question:'You can return to this idea.'}</p></article></div><div className="report-detail"><h3>{report.benchmarkComplete&&first?`${wpm(report.benchmark)-wpm(first.benchmark)>=0?'+':''}${Math.round((wpm(report.benchmark)-wpm(first.benchmark))*10)/10} WPM from your first full check`:'A little practice adds to your story.'}</h3><p>Practice words and full typing checks have different difficulty. Your chart compares full checks using the same passage.</p><p role="status" className={saved?'save-success':'save-note'}>{saveState}</p>{!saved&&identity.role!=='demo'&&<div className="button-row">{!report.learner&&identity.role==='teacher'&&<button className="soft" onClick={()=>setProfilesOpen(true)}>Choose a profile</button>}<button disabled={busy||(!report.learner&&!learner)} onClick={()=>{const r={...report,learner:report.learner||learner?.id||''};setReport(r);save(r)}}>{busy?'Saving…':'Save result'}</button></div>}</div><div className="button-row"><button disabled={!saved&&!!report.learner} onClick={()=>{setTab('progress');setReport(null)}}>See my progress <ChevronRight size={18}/></button><button className="soft" disabled={!saved&&!!report.learner} onClick={()=>{setReport(null);setLessonId(Math.min(50,lessonId+1))}}>Back to sessions</button></div></section>:
 <><div className="title-row"><div><p className="eyebrow" style={{color:unit.color}}>CHAPTER {lesson.unit+1} · {unit.name.toUpperCase()}</p><h1>{lesson.title}</h1><p className="subheading">Session {lessonId} of 50 <span>·</span> {active?stage.name:'A little focus. One key at a time.'}</p></div><button disabled={active} className="soft" onClick={()=>setLessonOpen(true)}><BookOpen size={18}/>Choose session</button></div>
 <div className="work-grid"><div className="workspace">
 {!active?<section className="start-card"><div className="card-label"><span className="pill">TODAY’S MISSION</span><span className="light-icon"><Keyboard size={28}/></span></div><h2>{lessonId===1?'Let’s find your keys.':lesson.title}</h2><p className="idea-text">{lesson.idea}</p><div className="mission-line"><span><Keyboard/> Type a little</span><span><Volume2/> Hear the idea</span><span><Star/> See your growth</span></div><div className="button-row"><button className="primary big" disabled={identity.role==='student'&&(!learner||loading)} onClick={start}><Play size={21} fill="currentColor"/>Start session {lessonId}</button>{readButton(lesson.idea)}</div><p className="muted">{learner?`Progress will be saved for ${learner.name}.`:'This is a practice visit. Results are not saved until you sign in to your student account.'}</p><div className="setup-note"><Hand size={22}/><div><strong>Get comfortable.</strong><p>Relax your shoulders. Keep wrists comfortable. Find F and J, or use the hand position that works for you.</p></div></div></section>:
 <section className="activity-card"><div className="activity-head"><span className="pill">{phase+1} / 10 · {stage.name.toUpperCase()}</span><button className="soft compact" onClick={()=>{setPaused(!paused);if(paused&&phase===8&&benchStarted&&!benchDone)setRunning(true)}}>{paused?<Play size={17}/>:<Pause size={17}/>} {paused?'Resume':'Pause'}</button></div>
 {paused?<div className="pause-screen"><Pause size={42}/><h2>Take your time.</h2><p>Your typing timer is paused.</p><button onClick={()=>{setPaused(false);if(phase===8&&benchStarted&&!benchDone)setRunning(true)}}>Ready to continue</button></div>:
 <>
 {stage.kind==='read'&&<div className="read-stage"><span className="light-icon"><Hand size={34}/></span><h2>Find a comfortable start.</h2><p>Let your shoulders relax. Place your hands lightly on the keyboard.</p><div className="key-pair"><kbd>f</kbd><kbd>j</kbd></div><p>Feel the bumps on <strong>F</strong> and <strong>J</strong>. Use a hand position that works for you.</p>{readButton('Let your shoulders relax. Place your hands lightly on the keyboard. Feel the bumps on F and J.')}<p className="small-note">Today: {lesson.idea}</p></div>}
 {stage.kind==='break'&&<div className="break-stage"><span className="light-icon"><Hand size={40}/></span><h2>Hands off. Eyes away.</h2><p>Look across the room. Stretch your fingers gently. Move in a way that feels comfortable.</p><p className="break-time">{clock(Math.max(0,Math.ceil(stage.minutes*60-phaseSeconds)))}</p><p className="muted">Your typing timer is resting, too.</p></div>}
 {isTyping&&<><div className="typing-intro"><h2>{phase===1?'Warm up your fingers.':phase===8?'Your two-minute check.':phase===4?'Practice the idea.':'Listen. Think. Type.'}</h2>{phase!==1&&phase!==8&&<p>{lesson.idea}</p>}<div className="button-row">{readButton(phase===8?'Type the passage carefully. The timer starts when you press Begin check. Spaces and punctuation count.':phase===1?'Type the highlighted key. A marked gap means press the space bar.':lesson.idea)}{phase===8&&<span className="benchmark-clock"><Clock size={18}/>{clock(Math.max(0,Math.ceil(120-bench.seconds)))}</span>}</div></div>
 {phase===8&&!benchStarted?<div className="benchmark-start"><p>Use the same passage each time. Work at your own pace for two minutes.</p><p className="sample-text">{benchmark}</p><button onClick={()=>{setBenchStarted(true);setRunning(true);capture.current?.focus()}}>Begin check <Play size={17}/></button></div>:benchDone&&phase===8?<div className="check-done"><CheckCircle2 size={38}/><h2>{wpm(bench)} WPM</h2><p>{accuracy(bench)}% accuracy · {bench.correct} correct keys</p><button onClick={movePhase}>See how I did <ChevronRight size={18}/></button></div>:
 <><div className="type-surface" onClick={()=>capture.current?.focus()}><div className="surface-top"><span>TYPE THIS</span><span>{phase===8?'Same passage every session':`Round ${round+1}`}</span></div><div className="phrase" aria-hidden="true">{target.split('').map((c,i)=><span key={i} className={`${i<pos?'typed':i===pos?'current':'upcoming'} ${c===' '?'space-char':''}`}>{c===' '?'␣':c}</span>)}</div><div className="next-key" aria-live="polite">{next===' '?<><kbd>SPACE</kbd><span>Tap the long space bar <strong>once</strong></span></>:<><kbd>{next==='\n'?'ENTER':next}</kbd><span>{/[A-Z]/.test(next)?'Hold Shift + press this letter':'Press this key'}{pos+1<target.length&&<small>Then: {target[pos+1]===' '?'SPACE':target[pos+1]}</small>}</span></>}</div><input ref={capture} className="typing-input" aria-label={`Typing area. Next key: ${next===' '?'space':next}. Text: ${target}`} value="" placeholder="Click here and type on your keyboard" onKeyDown={keydown} onChange={e=>{if(e.target.value)input(e.target.value.slice(-1))}} onPaste={e=>{e.preventDefault();setFlash('Type one key at a time.')}} autoComplete="off" autoCapitalize="off" spellCheck={false}/><p className={`typing-feedback ${flash.startsWith('Try')||flash.startsWith('Tap')?'retry':''}`} role="status">{flash||'One key at a time. You can take your time.'}</p></div>{showKeys&&<KeyBoard next={next}/>}<div className="typing-bottom"><span><Check size={16}/>{phase===8?bench.correct:metrics.correct} correct keys</span><span><Star size={16}/>{round} rounds</span><span>{phase===8?'':mode==='letters'?'Single-letter support':mode==='words'?'Word practice':'Phrase practice'}</span></div></>}
 </>}
 {stage.kind==='create'&&<div className="create-stage"><h2>Make the idea your own.</h2><p className="idea-text">{lesson.task}</p>{readButton(lesson.task)}<label htmlFor="draft">My work</label><textarea id="draft" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Type your idea here…" maxLength={5000} spellCheck={false}/><details><summary>I need a starting idea</summary><pre>{lesson.example}</pre><p>You can change this idea. Ask your teacher to help with longer words.</p></details>{lessonId>=33&&lessonId<=40&&<div className="code-runner"><button onClick={()=>setCodeOutput(runClassroomPython(draft))}><Play size={17}/>Run my code</button><p className="small-note">This small practice lab runs print, variables, named functions, range loops, and if. Use four spaces to indent. It supports the examples in these sessions.</p>{codeOutput&&<div role="status"><h3>Program output</h3><pre>{codeOutput.output||'No output yet.'}</pre>{codeOutput.error&&<p className="error">{codeOutput.error}</p>}</div>}</div>}</div>}
 {stage.kind==='check'&&<div className="concept-check"><span className="light-icon"><HelpCircle size={34}/></span><h2>What do you think?</h2><p className="idea-text">{lesson.question}</p>{readButton(lesson.question+' Your choices are '+lesson.choices.join(' or '))}<div className="answer-options">{lesson.choices.map(c=><span key={c}>{c}</span>)}</div><label htmlFor="answer">Type the word you choose</label><input id="answer" maxLength={300} value={check} onChange={e=>{setCheck(e.target.value);setCheckSubmitted(false)}} onKeyDown={e=>{if(e.key==='Enter')setCheckSubmitted(true)}} autoComplete="off" spellCheck={false}/><button disabled={!check.trim()} onClick={()=>setCheckSubmitted(true)}>Check my idea</button>{checkSubmitted&&<div className="answer-feedback" role="status"><strong>{check.trim().toLowerCase()===lesson.answer?'Yes, you have it.':'Let’s look at the idea again.'}</strong><p>{lesson.idea}</p>{check.trim().toLowerCase()!==lesson.answer&&<p>Try: <strong>{lesson.answer}</strong></p>}</div>}</div>}
 {stage.kind==='reflect'&&<div className="reflect-stage"><span className="achievement"><Star size={34}/></span><h2>Notice what you learned.</h2><p>You typed {metrics.correct+bench.correct} correct keys today.</p><label htmlFor="reflection">One thing I learned, or a goal for next time</label><textarea id="reflection" value={reflection} onChange={e=>setReflection(e.target.value)} placeholder="I learned…" maxLength={1000}/><p className="small-note">You can type one word, a short phrase, or ask someone to help you record your thought.</p><button className="big" onClick={finish}>Finish & save <Check size={20}/></button></div>}
 </>}
 {!paused&&stage.kind!=='reflect'&&<footer className="activity-footer"><span>{phase===8?'Typing check':`${stage.minutes}-minute section`} · {phase===8?'Continue when your check is done.':`${clock(Math.max(0,Math.ceil(stage.minutes*60-phaseSeconds)))} remaining`}</span><button className="soft" onClick={movePhase}>{phase===8&&!benchDone?'Skip check':stage.kind==='break'?'Ready now':'Next part'}<ChevronRight size={17}/></button></footer>}
 </section>}
 <div className="gentle-note"><Target size={18}/><span>Careful keys come first. Your goal is your own progress.</span></div>
 </div><aside className="session-side"><section className="routine-card"><div className="side-title"><h3>Our 42 minutes</h3><Clock size={18}/></div><ol className="routine">{phases.map((p,i)=><li key={p.name} className={active&&phase===i?'selected':active&&phase>i?'done':''}><span className="step-number">{active&&phase>i?<Check size={14}/>:i+1}</span><span>{p.name}</span><small>{p.minutes}m</small></li>)}</ol><p className="small-note">Pause when you need. Your teacher can move you to the next part.</p>{active&&<button className="text-button" onClick={()=>setConfirmExit(true)}>Finish early & save</button>}</section><section className="growth-card"><div className="side-title"><h3>Your growing skills</h3><Star size={19}/></div><p><strong>{completeIds.size}</strong> of 50 sessions explored</p><Progress value={completeIds.size/50*100} aria-label="Completed sessions"/><div className="mini-stats"><div><strong>{latest?wpm(latest.benchmark):'—'}</strong><span>latest WPM</span></div><div><strong>{latest?accuracy(latest.benchmark)+'%':'—'}</strong><span>accuracy</span></div></div>{!latest&&<p className="small-note">Your first full check gives you a starting point.</p>}</section></aside></div></>}
 </TabsContent>
 <TabsContent value="journey"><div className="title-row"><div><p className="eyebrow">YOUR COURSE</p><h1>One session at a time.</h1><p className="subheading">Five chapters. Fifty chances to build your skills.</p></div><span className="pill">{completeIds.size} / 50 explored</span></div><div className="chapters">{units.map((u,i)=><section className="chapter" key={u.name}><header><span className="chapter-number" style={{background:u.color}}>{String(i+1).padStart(2,'0')}</span><div><h2>{u.name}</h2><p>{u.desc}</p></div></header><div className="lesson-grid">{lessons.filter(l=>l.unit===i).map(l=><button key={l.id} className={`lesson-tile ${completeIds.has(l.id)?'completed':''}`} onClick={()=>{setLessonId(l.id);setTab('today')}}><span>{completeIds.has(l.id)?<Check size={18}/>:String(l.id).padStart(2,'0')}</span><strong>{l.title}</strong><ChevronRight size={16}/></button>)}</div></section>)}</div></TabsContent>
 <TabsContent value="progress"><div className="title-row"><div><p className="eyebrow">{learner?.name?.toUpperCase()||'YOUR LEARNING'}</p><h1>Look how far you’ve come.</h1><p className="subheading">Your practice, your pace.</p></div><button className="soft" disabled={!myResults.length} onClick={csvExport}><Download size={18}/>Export my results</button></div>{!learner&&<div className="notice">Choose your profile to see your saved progress.<button onClick={()=>setProfilesOpen(true)}>Choose profile</button></div>}<div className="metric-grid"><article><span>Latest full check</span><strong>{latest?wpm(latest.benchmark):'—'} <small>WPM</small></strong></article><article><span>Latest accuracy</span><strong>{latest?accuracy(latest.benchmark)+'%':'—'}</strong></article><article><span>Change from first check</span><strong>{latest?`${gain>=0?'+':''}${gain}`:'—'} <small>WPM</small></strong></article><article><span>Sessions explored</span><strong>{completeIds.size} <small>/ 50</small></strong></article></div><div className="progress-layout"><section className="panel"><h2>My typing over time</h2><Trend results={myResults}/></section><section className="panel"><h2>My milestones</h2><div className="milestone-list">{[{name:'First steps',n:1},{name:'Finding a rhythm',n:5},{name:'Keyboard explorer',n:10},{name:'Halfway there',n:25},{name:'Course explorer',n:50}].map(b=><div className={completeIds.size>=b.n?'earned':''} key={b.name}><Star size={23} fill={completeIds.size>=b.n?'currentColor':'none'}/><div><strong>{b.name}</strong><small>{b.n} sessions explored</small></div>{completeIds.size>=b.n&&<Check size={17}/>}</div>)}</div></section></div><section className="panel"><h2>Session history</h2>{myResults.length?<History results={myResults}/>:<p className="muted">Your saved sessions will appear here.</p>}<details><summary>What do these numbers mean?</summary><p>WPM = correct characters ÷ 5 ÷ active minutes. Accuracy = correct key presses ÷ all attempted character key presses. Wrong keys are counted and must be retried. Spaces and punctuation count. Held keys and pasted text do not count. Practice time starts with the first key in a typing section; the two-minute check starts at Begin check. Pauses and time on other screens are excluded. Your chart uses only full 120-second checks on the same passage, including pauses if used. Repeat familiarity can improve scores. These are supported copying measures; writing and concept questions are measured separately.</p></details></section></TabsContent>
 {identity.role==='teacher'&&<TabsContent value="teacher"><Teacher lessons={lessons} results={results} learners={learners} loadError={loadError} loading={loading} retry={load} add={()=>setProfilesOpen(true)} csv={csvExport} select={(id)=>{setLessonId(id);setTab('today')}}/></TabsContent>}
 </Tabs></div>
 <Dialog open={profilesOpen} onOpenChange={setProfilesOpen}><DialogContent className="dialog"><DialogHeader><DialogTitle>Choose your profile</DialogTitle><DialogDescription>Add a nickname to create a student account. Give the student the class code and their personal code.</DialogDescription></DialogHeader>{loading?<p>Loading profiles…</p>:loadError?<div className="error"><p>{loadError}</p><button onClick={load}>Try again</button><button onClick={onSignOut}>Return to sign-in</button></div>:<div className="profile-grid">{learners.map(l=><div key={l.id}><button className="soft" onClick={()=>chooseLearner(l)}><UserRound size={20}/>{l.name}</button><button className="soft" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await request('/functions/v1/keyquest-admin',{method:'POST',body:JSON.stringify({action:'reset',learnerId:l.id})});setLastCode({name:l.name,code:r.studentCode})}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}}>New code</button></div>)}</div>}<form onSubmit={e=>{e.preventDefault();addLearner()}}><label htmlFor="nickname">Add a classroom nickname</label><div className="inline-form"><input id="nickname" maxLength={40} placeholder="e.g. Blue Fox" value={newName} onChange={e=>setNewName(e.target.value)}/><button disabled={busy||!newName.trim()}><Plus size={18}/>{busy?'Saving…':'Add'}</button></div></form><p className="small-note">Students see their own progress. The teacher can view the whole class. Student codes are shown when created or reset.</p></DialogContent></Dialog>
 <Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent className="dialog"><DialogHeader><DialogTitle>Learning settings</DialogTitle><DialogDescription>Choose supports before a session. These settings stay on this device.</DialogDescription></DialogHeader><label>Practice text length</label><Select value={mode} onValueChange={setMode}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="letters">One letter at a time</SelectItem><SelectItem value="words">Short words</SelectItem><SelectItem value="phrases">Short phrases</SelectItem></SelectContent></Select><p className="small-note">All levels hear the same concept. Warm-ups build from home keys. The progress check always uses the same passage.</p><div className="setting"><label htmlFor="large">Larger typing text</label><Switch id="large" checked={large} onCheckedChange={setLarge}/></div><div className="setting"><label htmlFor="keys">Show keyboard guide</label><Switch id="keys" checked={showKeys} onCheckedChange={setShowKeys}/></div><button onClick={()=>setSettingsOpen(false)}>Done</button></DialogContent></Dialog>
 <Dialog open={lessonOpen} onOpenChange={setLessonOpen}><DialogContent className="dialog lesson-dialog"><DialogHeader><DialogTitle>Choose a session</DialogTitle><DialogDescription>You can repeat any lesson or choose the class’s current session.</DialogDescription></DialogHeader><div className="session-picker">{lessons.map(l=><button className="soft" key={l.id} onClick={()=>{setLessonId(l.id);setLessonOpen(false)}}><span>{String(l.id).padStart(2,'0')}</span>{l.title}</button>)}</div></DialogContent></Dialog>
 <Dialog open={confirmExit} onOpenChange={setConfirmExit}><DialogContent className="dialog"><DialogHeader><DialogTitle>Finish this session early?</DialogTitle><DialogDescription>You can save the practice you have done. This session will be marked as partial.</DialogDescription></DialogHeader><div className="button-row"><button onClick={()=>{setConfirmExit(false);finish()}}>Save & finish</button><button className="soft" onClick={()=>setConfirmExit(false)}>Keep practicing</button></div></DialogContent></Dialog>
 <Dialog open={!!lastCode} onOpenChange={v=>{if(!v)setLastCode(null)}}><DialogContent className="dialog"><DialogHeader><DialogTitle>{lastCode?.name} · sign-in card</DialogTitle><DialogDescription>Copy these codes before closing. A new student code replaces the previous code.</DialogDescription></DialogHeader><p>Class code: <strong>{identity.classCode}</strong></p><p>Student code: <strong className="student-code">{lastCode?.code}</strong></p><p className="small-note">These codes are all this student needs to sign in. Save them in your classroom records.</p><button onClick={()=>setLastCode(null)}>Done</button></DialogContent></Dialog><footer className="site-footer"><span>KeyQuest · A supported path into computer science</span><span>NY grades 7–8 · Classroom edition</span></footer></div>
}
function History({results}:{results:Result[]}){return <Table><TableHeader><TableRow><TableHead>Date</TableHead><TableHead>Session</TableHead><TableHead>Check WPM</TableHead><TableHead>Accuracy</TableHead><TableHead>Idea check</TableHead><TableHead>Work</TableHead></TableRow></TableHeader><TableBody>{[...results].reverse().map(r=><TableRow key={r.id}><TableCell>{new Date(r.created).toLocaleDateString()}</TableCell><TableCell>{r.lesson}{!r.complete?' · partial':''}</TableCell><TableCell>{r.benchmark.seconds?wpm(r.benchmark):'—'}{r.benchmark.seconds>0&&!r.benchmarkComplete?' (partial)':''}</TableCell><TableCell>{r.benchmark.attempts?accuracy(r.benchmark)+'%':'—'}</TableCell><TableCell>{r.check?(r.checkCorrect?'Correct':'Revisit'):'Not answered'}</TableCell><TableCell><details><summary>View</summary><p><strong>Answer:</strong> {r.check||'—'}</p><pre>{r.draft||'No writing recorded.'}</pre><p>{r.reflection}</p></details></TableCell></TableRow>)}</TableBody></Table>}
function Teacher({lessons,results,learners,loadError,loading,retry,add,csv,select}:{lessons:Lesson[];results:Result[];learners:Learner[];loadError:string;loading:boolean;retry:()=>void;add:()=>void;csv:()=>void;select:(id:number)=>void}){const [student,setStudent]=useState('all');return <><div className="title-row"><div><p className="eyebrow">TEACHER WORKSPACE</p><h1>A routine you can return to.</h1><p className="subheading">50 sessions · 42 minutes · 35 hours of supported learning</p></div><div className="button-row"><button className="soft" onClick={add}><Plus size={18}/>Add profile</button><button disabled={!results.length} onClick={csv}><Download size={18}/>Export class data</button></div></div>{loadError&&<div className="error"><p>{loadError}</p><button onClick={retry}>Retry loading</button></div>}<section className="panel teacher-intro"><h2>Start with the learner in front of you.</h2><p>This course directly practices keyboarding toward <strong>7–8.DL.1</strong>. The computing lessons provide adapted entry points across the five NY domains. Copying vocabulary alone does not demonstrate a grade-band standard; use the typed decisions, original work, discussion, and transfer tasks as evidence.</p><div className="teacher-columns"><div><h3>For a student around 4 WPM</h3><p>Begin with letters or short words. Read the concept aloud together. Model one key, practice together, then let the student try. Keep the keyboard guide visible. Repeat a session as needed; the 50-session sequence is a pacing guide.</p></div><div><h3>During the 42 minutes</h3><p>Read and discuss within learning rounds. Each typing section cycles short prompts until its time ends. Two planned breaks and flexible pauses support stamina. Move to the next part early when needed. Original writing and the idea check stay separate from speed data.</p></div><div><h3>Look for understanding</h3><p>Ask students to explain or demonstrate their typed choice. Record support needs alongside your classroom notes. Revisit missed concepts. Use the final project tasks to look for transfer beyond familiar copied sentences.</p></div></div><details><summary>Profiles, access, and progress</summary><p>Students sign in with a class code and an eight-digit student code. Their results follow them between computers. Student access is restricted to their own records by database policies; the teacher can see the class. Add students using nicknames, and keep each code private. Use New code to replace a lost student code. Sign out at the end of shared-computer use.</p><p>Results save when a learner finishes. If a save fails, the result remains on screen for retry. Refreshing or closing an unfinished session discards unsaved work. CSV export includes both measurements and the student’s typed work.</p></details></section>
 <section className="panel"><div className="title-row small"><h2>Class progress</h2><button className="soft" onClick={retry}><RotateCcw size={17}/>Refresh</button></div>{loading?<p>Loading your class…</p>:!learners.length?<div className="empty-chart"><UserRound/><h3>Add your first classroom profile.</h3><p>Use a nickname, then complete a session to begin collecting progress.</p><button onClick={add}>Add profile</button></div>:<Table><TableHeader><TableRow><TableHead>Learner</TableHead><TableHead>Explored</TableHead><TableHead>First WPM</TableHead><TableHead>Latest WPM</TableHead><TableHead>Accuracy</TableHead><TableHead>Practice next</TableHead></TableRow></TableHeader><TableBody>{learners.map(l=>{const own=results.filter(r=>r.learner===l.id),valid=own.filter(r=>r.benchmarkComplete),last=valid.at(-1),errs=own.reduce((all:Record<string,number>,r)=>{for(const [k,v] of Object.entries(r.errors))all[k]=(all[k]||0)+v;return all},{});return <TableRow key={l.id}><TableCell><button className="text-button" onClick={()=>setStudent(l.id)}>{l.name}</button></TableCell><TableCell>{new Set(own.filter(r=>r.complete).map(r=>r.lesson)).size}/50</TableCell><TableCell>{valid[0]?wpm(valid[0].benchmark):'—'}</TableCell><TableCell>{last?wpm(last.benchmark):'—'}</TableCell><TableCell>{last?accuracy(last.benchmark)+'%':'—'}</TableCell><TableCell>{Object.entries(errs).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([k])=>k===' '?'SPACE':k).join(', ')||'Collect a session'}</TableCell></TableRow>})}</TableBody></Table>}</section>
 {student!=='all'&&<section className="panel"><div className="title-row small"><h2>{learners.find(l=>l.id===student)?.name} · Work & history</h2><button className="soft" onClick={()=>setStudent('all')}>Close history</button></div><History results={results.filter(r=>r.learner===student)}/></section>}
 <section className="panel"><h2>Course guide & standards connections</h2><p>Every session includes keyboarding. Codes below identify additional connections or an explicit keyboarding focus. Grade-level programming, collaboration, publishing, and modeling require supported application; the small Python practice lab runs the supported examples in sessions 33–40.</p><div className="standards-note"><strong>Evidence beyond copied text</strong><p>Sessions 33–40: build and test small programs in the built-in practice lab; extend them in your Python classroom tool when ready. Sessions 41–43: collect data, use the progress chart, and compare model assumptions. Sessions 48–49: work with a partner and revise a digital product. For complete standards evidence, extend these tasks to the full grade-band expectations.</p></div><Table><TableHeader><TableRow><TableHead>Session</TableHead><TableHead>Focus</TableHead><TableHead>Connection</TableHead><TableHead>Student work / teacher prompt</TableHead></TableRow></TableHeader><TableBody>{lessons.map(l=><TableRow key={l.id}><TableCell><button className="text-button" onClick={()=>select(l.id)}>{String(l.id).padStart(2,'0')}</button></TableCell><TableCell>{l.title}</TableCell><TableCell className="nowrap">{l.standard}</TableCell><TableCell>{l.task}</TableCell></TableRow>)}</TableBody></Table></section><section className="panel sources"><h2>Teaching references</h2><p>The daily pacing and adapted examples are designed for this course. Adjust supports to each learner’s access needs.</p><a href="https://www.nysed.gov/standards-instruction/computer-science-and-digital-fluency" target="_blank" rel="noreferrer">NYSED · Computer Science and Digital Fluency Standards</a><a href="https://www.nysed.gov/sites/default/files/programs/standards-instruction/computer-science-digital-fluency-standards-7-8.pdf" target="_blank" rel="noreferrer">NYSED · Grade 7–8 standards</a><a href="https://www.typing.com/student/lesson/33075/j-f-and-space" target="_blank" rel="noreferrer">Typing.com · F, J, and space progression</a><a href="https://www.typing.com/student/lesson/335/accuracy-drills" target="_blank" rel="noreferrer">Typing.com · Accuracy practice</a><a href="https://www.typing.com/blog/typing-posture/" target="_blank" rel="noreferrer">Typing.com · Keyboard posture guidance</a></section></>}
