// Five exact-copy scenes make a small story with a visible ending.
export const stories=[
 {title:'The missing pizza',icon:'🍕',lines:['the pizza is gone','a cat has the box','the box is empty','look under the hat','the cat hid a slice'],reveals:['Follow the cheese trail.','The cat looks very full.','One slice is still missing.','That is a very tall hat.','Case solved. The last slice is safe.']},
 {title:'Dino at the door',icon:'🦖',lines:['a dino rings the bell','he has a tiny bag','the bag starts to beep','a duck pops out','the duck wants lunch'],reveals:['Someone big is waiting.','Something is moving inside.','Is that an alarm?','The duck packed itself.','Lunch for two. Mystery solved.']},
 {title:'Robot dance off',icon:'🤖',lines:['the robot hears a beat','it spins on one foot','its hat flies off','the cat wears the hat','the cat wins the dance'],reveals:['The dance floor lights up.','One more spin.','The hat lands on a cat.','The cat has a new move.','The crowd cheers for the cat.']},
 {title:'Moon snack delivery',icon:'🚀',lines:['pack the moon snacks','the ship will not go','a frog is on the switch','give the frog a chip','we land on the moon'],reveals:['The moon crew is hungry.','Check the big red switch.','The frog wants a snack too.','The ship lifts off.','Delivery complete. Time to eat.']},
 {title:'The ghost in the game',icon:'👻',lines:['a ghost joins the game','it walks through a wall','it gets stuck in a chair','we pull it out','the ghost says thanks'],reveals:['A new player appears.','That looks like a shortcut.','The chair has other plans.','Teamwork saves the ghost.','You made a new teammate.']},
 {title:'Shark talent show',icon:'🦈',lines:['the shark has a mic','it sings one loud note','the crab drops its drum','the fish start to dance','the band takes a bow'],reveals:['The show is starting.','Even the waves shake.','The drum makes a new beat.','The whole reef joins in.','First show complete. Encore.']},
 {title:'The tiny race',icon:'🏁',lines:['a snail joins the race','a duck waves the flag','the rabbit takes a nap','the snail keeps going','the snail wins a cup'],reveals:['The smallest racer is ready.','The race is on.','The track is quiet.','The finish line is close.','A win for the snail.']},
 {title:'A very odd pet',icon:'🐉',lines:['i find a small egg','the egg starts to crack','a dragon pops out','it sneezes on my toast','breakfast is ready'],reveals:['The egg feels warm.','Something is waking up.','This pet will need a big bed.','The toast is now golden.','Your pet has a breakfast job.']},
 {title:'The hat machine',icon:'🎩',lines:['the robot makes a hat','the hat is too big','the hat fills the room','we turn the dial down','now the hat fits a pea'],reveals:['A new hat is on the way.','It is still growing.','Where is the door?','The machine starts to shrink it.','A very small fashion show.']},
 {title:'Skate park surprise',icon:'🛹',lines:['a duck gets a board','it rolls down the ramp','a cat jumps on','they roll past the pond','the fish want a turn'],reveals:['First trip to the skate park.','The duck is getting the hang of it.','Now there are two riders.','The pond crowd cheers.','A line forms for the next ride.']},
 {title:'The secret button',icon:'🔴',lines:['we find a red button','the sign says press me','we press it once','the floor fills with balls','the robot wants to play'],reveals:['What could it do?','The robot is watching.','A hatch opens above us.','It is a giant ball pit.','Play room unlocked.']},
 {title:'Monster movie night',icon:'🍿',lines:['the monster makes popcorn','the bowl starts to shake','a mouse jumps out','it has the remote','the mouse picks the movie'],reveals:['The room smells like popcorn.','There is someone in the bowl.','The smallest guest has arrived.','The monster gets a seat.','Movie night can finally start.']}
];
export function storyAt(steps:number){const n=Math.max(0,Math.floor(steps));const story=stories[Math.floor(n/5)%stories.length];const scene=n%5;return {...story,scene,text:story.lines[scene],reveal:story.reveals[scene],finished:scene===4};}

export function storyPassage(steps:number){const s=storyAt(steps);return {...s,text:s.lines.join('. ')+'.',scene:0};}
